---
title: "chondrocyte analysis"
output: html_document
date: '2023-03-22'
---


```{r}
seurat_chondro <- subset(seurat_revised, subset = condition == 'D00' | condition == 'D0' | condition == 'D7c' | condition == 'D14c')

save(seurat_chondro, file = "seurat_chondro.RData")

library(dplyr)
library(Seurat)
library(patchwork)
library(ggplot2)

#Seurat objects being used
NA18856 <- subset(seurat_chondro, subset = donor_id == 'NA18856')
NA18855 <- subset(seurat_chondro, subset = donor_id == 'NA18855')
NA19160 <- subset(seurat_chondro, subset = donor_id == 'NA19160')

seurat_chondro<- subset(seurat_chondro, subset = nFeature_RNA > 200 & nFeature_RNA < 6000 & percent.mt < 5)
wu_combined_rev<- subset(wu_combined_rev, subset = nFeature_RNA > 200 & nFeature_RNA < 6000 & percent.mt < 5)

#Creating a list of the Seurat objects
individual_list <- list(NA18856, NA18855, NA19160)

# normalize and identify variable features for each dataset independently
individual_list <- lapply(X = individual_list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

#Select features that are repeatedly variable across data sets for integration
features <- SelectIntegrationFeatures(object.list = individual_list)
cell.anchors <- FindIntegrationAnchors(object.list = individual_list, anchor.features = features)

#Creating the integrated data set
cells.combined <- IntegrateData(anchorset = cell.anchors)
DefaultAssay(cells.combined) <- "integrated"

#Standard workflow for visualization and clustering 
cells.combined <- ScaleData(cells.combined, verbose = FALSE)
cells.combined <- RunPCA(cells.combined, npcs = 50, verbose = FALSE)

#Trying to find how many PCs to include
ElbowPlot(cells.combined)
save(cells.combined, file = "cells.combined.chondro.pc.RData")

#Try 15, 20, and 50 PCs

cells.combined <- RunUMAP(cells.combined, reduction = "pca", dims = 1:30)
cells.combined <- FindNeighbors(cells.combined, reduction = "pca", dims = 1:30)
cells.combined <- FindClusters(cells.combined, resolution = 0.2)

# Visualization
p1 <- DimPlot(cells.combined, reduction = "umap", split.by = "condition")
p2 <- DimPlot(cells.combined, reduction = "umap", label = TRUE, repel = TRUE)
p1 + p2

DimPlot(object = cells.combined, reduction = 'umap', group.by = "condition",cols = c("D7c" = rgb(253, 93, 93, maxColorValue = 255), "D00" = rgb(186, 85, 211, maxColorValue=255), c("D0" = rgb(218, 75, 180, maxColorValue = 255),"Wu_chondrogenic_pellet_d7"=rgb(211,211,211, maxColorValue = 255), "Wu_chondrogenic_pellet_d14"=rgb(132,136,132, maxColorValue = 255), "Wu_chondrogenic_pellet_d28"=rgb(113,121,126, maxColorValue = 255), "Wu_chondrogenic_pellet_d42"=rgb(54,69,79, maxColorValue = 255) ,"D14c" = rgb(254, 192, 0, maxColorValue = 255))))

# Create a vector of ordered timepoints
ordered_timepoints <- factor(cells.combined@meta.data$condition, levels = c("D00", "D0", "D7c", "D14c"), ordered = TRUE)

# Add the ordered timepoints as a new column in the metadata
cells.combined@meta.data$timepoints_ordered <- ordered_timepoints

# Use the new column in the split.by argument of the DimPlot function
DimPlot(cells.combined, reduction = "umap", split.by = "timepoints_ordered", label=TRUE)


DimPlot(cells.combined, reduction = "umap", split.by = "condition", label=TRUE)


Idents(cells.combined) <- factor(Idents(cells.combined))

markers.to.plot <- c("SOX9", "SOX5", "SOX6", "MATN3", "SPARC", "COL11A1")


DefaultAssay(cells.combined) <- "RNA"
DotPlot(cells.combined, features = markers.to.plot, cols = c("red", "blue"), dot.scale = 8) +
    RotatedAxis()

plots <- VlnPlot(cells.combined, features = c("COL11A1"),
    pt.size = 0, combine = FALSE)
wrap_plots(plots = plots, ncol = 1)

cells.combined <- RenameIdents(cells.combined, `0` = "D0", `2` = "D00 A", `3` = "D00 B",
    `1` = "D14c/D7c A", `4` = "D14c/D7c B", `5`='N/A 5', `6`='NA 6', `7`='NA 7', `8`='NA 8' )
DimPlot(cells.combined, label = TRUE)

plots <- VlnPlot(cells.combined, features = c("SPARC6"),
    pt.size = 0, combine = FALSE)
wrap_plots(plots = plots, ncol = 1)
```

```{r}
wu_combined<- subset(wu_combined, subset = nFeature_RNA > 200 & nFeature_RNA < 6000 & percent.mt < 5)

wu_combined <- NormalizeData(wu_combined, normalization.method = "LogNormalize", scale.factor = 10000)


wu_combined <- FindVariableFeatures(wu_combined, selection.method = "vst", nfeatures = 2000)

all.genes <- rownames(wu_combined)
wu_combined <- ScaleData(wu_combined, features = all.genes)

wu_combined  <- RunPCA(wu_combined , features = VariableFeatures(object = wu_combined ))
ElbowPlot(wu_combined)


wu_combined <- FindNeighbors(wu_combined, dims = 1:30)
wu_combined1 <- FindClusters(wu_combined, resolution = 0.5)






wu_combined1 <- RunUMAP(wu_combined1, dims = 1:30)
DimPlot(wu_combined1, reduction = "umap",group.by = "Cell.Type")

DimPlot(wu_combined1, reduction = "umap", split.by = "Cell.Type", label=TRUE)

Idents(cells.combined) <- factor(Idents(cells.combined))

markers.to.plot <- c("SOX9", "SOX5", "SOX6", "COL2A1", "ACAN", "COL9A1", "MATN3", "SPARC", "COL11A1",
    "PRG4")

DefaultAssay(cells.combined) <- "RNA"
DotPlot(cells.combined, features = markers.to.plot, cols = c("grey", "blue"), dot.scale = 8, col.min=0) +
    RotatedAxis()

DotPlot(
  object,
  assay = NULL,
  features,
  cols = c("lightgrey", "blue"),
  col.min = -2.5,
  col.max = 2.5,
  dot.min = 0,
  dot.scale = 6,
  idents = NULL,
  group.by = NULL,
  split.by = NULL,
  cluster.idents = FALSE,
  scale = TRUE,
  scale.by = "radius",
  scale.min = NA,
  scale.max = NA
)

```


```{r}
names1 <- cells.combined@meta.data[["condition"]]
names2 <- cells.combined@meta.data[["Cell.Type"]]
length1 <- length (cells.combined@meta.data[["condition"]])
length2 <- length

# Check if the names and lengths are the same
if (identical(names1, names2) && length1 == length2) {
  print("The metadata fields are in the same order.")
} else {
  print("The metadata fields are not in the same order.")
}


seurat_r_df= cells.combined@meta.data


cells.combined[["merged_field"]] <- ifelse(is.na(cells.combined[["condition"]]), cells.combined[["Cell.Type"]], cells.combined[["condition"]])

```



